/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as ApiCopilotRouteImport } from './routes/api/copilot'
import { Route as AuthenticatedWorkflowRouteImport } from './routes/_authenticated/workflow'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedFilaRouteImport } from './routes/_authenticated/fila'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedClientesClientIdRouteImport } from './routes/_authenticated/clientes_.$clientId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotRoute = ApiCopilotRouteImport.update({
  id: '/api/copilot',
  path: '/api/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkflowRoute = AuthenticatedWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilaRoute = AuthenticatedFilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesClientIdRoute =
  AuthenticatedClientesClientIdRouteImport.update({
    id: '/clientes_/$clientId',
    path: '/clientes/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/portal/$token': typeof PortalTokenRoute
  '/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/portal/$token': typeof PortalTokenRoute
  '/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/fila': typeof AuthenticatedFilaRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/_authenticated/workflow': typeof AuthenticatedWorkflowRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/portal/$token': typeof PortalTokenRoute
  '/_authenticated/clientes_/$clientId': typeof AuthenticatedClientesClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/biblioteca'
    | '/calendario'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/equipe'
    | '/fila'
    | '/financeiro'
    | '/marketing'
    | '/tarefas'
    | '/videos'
    | '/workflow'
    | '/api/copilot'
    | '/portal/$token'
    | '/clientes/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/biblioteca'
    | '/calendario'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/equipe'
    | '/fila'
    | '/financeiro'
    | '/marketing'
    | '/tarefas'
    | '/videos'
    | '/workflow'
    | '/api/copilot'
    | '/portal/$token'
    | '/clientes/$clientId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/biblioteca'
    | '/_authenticated/calendario'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipe'
    | '/_authenticated/fila'
    | '/_authenticated/financeiro'
    | '/_authenticated/marketing'
    | '/_authenticated/tarefas'
    | '/_authenticated/videos'
    | '/_authenticated/workflow'
    | '/api/copilot'
    | '/portal/$token'
    | '/_authenticated/clientes_/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiCopilotRoute: typeof ApiCopilotRoute
  PortalTokenRoute: typeof PortalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot': {
      id: '/api/copilot'
      path: '/api/copilot'
      fullPath: '/api/copilot'
      preLoaderRoute: typeof ApiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workflow': {
      id: '/_authenticated/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AuthenticatedWorkflowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fila': {
      id: '/_authenticated/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof AuthenticatedFilaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes_/$clientId': {
      id: '/_authenticated/clientes_/$clientId'
      path: '/clientes/$clientId'
      fullPath: '/clientes/$clientId'
      preLoaderRoute: typeof AuthenticatedClientesClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFilaRoute: typeof AuthenticatedFilaRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedWorkflowRoute: typeof AuthenticatedWorkflowRoute
  AuthenticatedClientesClientIdRoute: typeof AuthenticatedClientesClientIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFilaRoute: AuthenticatedFilaRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedWorkflowRoute: AuthenticatedWorkflowRoute,
  AuthenticatedClientesClientIdRoute: AuthenticatedClientesClientIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiCopilotRoute: ApiCopilotRoute,
  PortalTokenRoute: PortalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
